import java.io.Serializable;

public class CheckBoxSO implements Serializable {
    private String optionId;

    private String mlingualCode;

    private String optionValue;

    public CheckBoxSO() {
    }

    public CheckBoxSO(String optionId, String mlingualCode, String optionValue) {
        this.optionId = optionId;
        this.mlingualCode = mlingualCode;
        this.optionValue = optionValue;
    }

    public String getOptionId() {
        return this.optionId;
    }

    public String getMlingualCode() {
        return this.mlingualCode;
    }

    public String getOptionValue() {
        return this.optionValue;
    }

    /**
     * @generated by CodeSugar http://sourceforge.net/projects/codesugar */

    public String toString() {
        StringBuffer buffer = new StringBuffer();
        buffer.append("[CheckBoxSO:");
        buffer.append(" optionId: ");
        buffer.append(optionId);
        buffer.append(" mlingualCode: ");
        buffer.append(mlingualCode);
        buffer.append(" optionValue: ");
        buffer.append(optionValue);
        buffer.append("]");
        return buffer.toString();
    }
}
