public class FieldTypeSO {
    static public final String READ_ONLY = "READ_ONLY", TEXT_BOX = "TEXT_BOX", TEXT_AREA = "TEXT_AREA", TEXT_DATE = "TEXT_DATE",
            DROP_DOWN_BOX = "DROP_DOWN_BOX", RADIO_BUTTON = "RADIO_BUTTON", HIDDEN_FIELD = "HIDDEN_FIELD", BOOLEAN_FIELD = "BOOLEAN_FIELD",
            CHECKBOX = "CHECKBOX", CHECKBOX_LIST = "CHECKBOX_LIST", MULTISELECT = "MULTISELECT", CUSTOM = "CUSTOM";
}
