
import java.io.Serializable;
import java.util.HashMap;
import java.util.Map;

public class FormPageSO implements Serializable {
    private String pageID;

    private String pageCaption;

    private PageSectionSO[] pageSection;

    private Map pageSectionMap;

    public FormPageSO() {
    }

    public FormPageSO(String pageID, String pageCaption, PageSectionSO[] pageSection) {
        this.pageID = pageID;
        this.pageCaption = pageCaption;
        this.pageSection = pageSection;
        this.pageSectionMap = new HashMap();
        for (int i = 0; i < this.pageSection.length; i++)
            this.pageSectionMap.put(this.pageSection[i].getSectionID(), this.pageSection[i]);
    }

    public String getPageID() {
        return this.pageID;
    }

    public String getPageCaption() {
        return this.pageCaption;
    }

    public void setPageID(String pageID) {
        this.pageID = pageID;
    }

    public void setPageCaption(String pageCaption) {
        this.pageCaption = pageCaption;
    }

    public PageSectionSO[] getPageSection() {
        return this.pageSection;
    }

    public PageSectionSO getPageSection(String pageSectionId) {
        return (PageSectionSO) this.pageSectionMap.get(pageSectionId);
    }

//    public String toString() {
//        String str = "pageID=[" + pageID + "],pageCaption=[" + pageCaption + "]";
//        return str;
//
//    }
    /**
     * @generated by CodeSugar http://sourceforge.net/projects/codesugar */

    public String toString() {
        StringBuffer buffer = new StringBuffer();
        buffer.append("[FormPageSO:");
        buffer.append(" pageID: ");
        buffer.append(pageID);
        buffer.append(" pageCaption: ");
        buffer.append(pageCaption);
        buffer.append(" { ");
        for (int i0 = 0; pageSection != null && i0 < pageSection.length; i0++) {
            buffer.append(" pageSection[" + i0 + "]: ");
            buffer.append(pageSection[i0]);
        }
        buffer.append(" } ");
        buffer.append(" pageSectionMap: ");
        buffer.append(pageSectionMap);
        buffer.append("]");
        return buffer.toString();
    }
}
