public class OptionSO {
    private String optionId;

    private boolean valueDefault;

    private String mlingualCode;

    private String optionValue;

    public OptionSO() {
    }

    public OptionSO(String optionId, boolean valueDefault, String mlingualCode, String optionValue) {
        this.optionId = optionId;
        this.valueDefault = valueDefault;
        this.mlingualCode = mlingualCode;
        this.optionValue = optionValue;
    }

    public String getOptionId() {
        return optionId;
    }

    public boolean isValueDefault() {
        return valueDefault;
    }

    public String getMlingualCode() {
        return mlingualCode;
    }

    public String getOptionValue() {
        return optionValue;
    }
    /**
     * @generated by CodeSugar http://sourceforge.net/projects/codesugar */

    public String toString() {
        StringBuffer buffer = new StringBuffer();
        buffer.append("[OptionSO:");
        buffer.append(" optionId: ");
        buffer.append(optionId);
        buffer.append(" valueDefault: ");
        buffer.append(valueDefault);
        buffer.append(" mlingualCode: ");
        buffer.append(mlingualCode);
        buffer.append(" optionValue: ");
        buffer.append(optionValue);
        buffer.append("]");
        return buffer.toString();
    }
}
