class PageSO {
    private String pageID;

    private String pageCaption;

    private PageSectionSO[] pageSection;

    public PageSO() {

    }

    public PageSO(String pageID, String pageCaption, PageSectionSO[] pageSection) {
        this.pageID = pageID;
        this.pageCaption = pageCaption;
        this.pageSection = pageSection;
    }

    public String getPageID() {
        return this.pageID;
    }

    public String getPageCaption() {
        return this.pageCaption;
    }

    public PageSectionSO[] getPageSection() {
        return this.pageSection;
    }
    /**
     * @generated by CodeSugar http://sourceforge.net/projects/codesugar */

    public String toString() {
        StringBuffer buffer = new StringBuffer();
        buffer.append("[PageSO:");
        buffer.append(" pageID: ");
        buffer.append(pageID);
        buffer.append(" pageCaption: ");
        buffer.append(pageCaption);
        buffer.append(" { ");
        for (int i0 = 0; pageSection != null && i0 < pageSection.length; i0++) {
            buffer.append(" pageSection[" + i0 + "]: ");
            buffer.append(pageSection[i0]);
        }
        buffer.append(" } ");
        buffer.append("]");
        return buffer.toString();
    }
}
