

public class PartnerAttachmentSO extends AttachmentSO {
    protected String id;

    protected String title;

    protected String description;

    protected String hyperlink;

    public PartnerAttachmentSO() {
        super();
    }

    public String getId() {
        return this.id;
    }

    public String getTitle() {
        return this.title;
    }

    public String getDescription() {
        return this.description;
    }

    public String getHyperlink() {
        return this.hyperlink;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void setHyperlink(String hyperlink) {
        this.hyperlink = hyperlink;
    }

//    public String toString() {
//        StringBuffer sb = new StringBuffer();
//        sb.append("id:[" + id + "]\r\n");
//        sb.append("title:[" + title + "]\r\n");
//        sb.append("description:[" + description + "]\r\n");
//        sb.append("filename:[" + filename + "]\r\n");
//        sb.append("filesize:[" + filesize + "]\r\n");
//        sb.append("hyperlink:[" + hyperlink + "]\r\n");
//        sb.append("mimetype:[" + mimetype + "]\r\n");
//        sb.append("content:[" + getContent() + "]\r\n");
//        return sb.toString();
//    }

    /**
     * @generated by CodeSugar http://sourceforge.net/projects/codesugar */

    public String toString() {
        StringBuffer buffer = new StringBuffer();
        buffer.append("[PartnerAttachmentSO:");
        buffer.append(" filename: ");
        buffer.append(filename);
        buffer.append(" filesize: ");
        buffer.append(filesize);
        buffer.append(" mimetype: ");
        buffer.append(mimetype);
        //it would print too many logs if debug is enabled
       /* buffer.append(" { ");
        for (int i0 = 0; content != null && i0 < content.length; i0++) {
            buffer.append(" content[" + i0 + "]: ");
            buffer.append(content[i0]);
        }
        buffer.append(" } ");*/
        buffer.append(" id: ");
        buffer.append(id);
        buffer.append(" title: ");
        buffer.append(title);
        buffer.append(" description: ");
        buffer.append(description);
        buffer.append(" hyperlink: ");
        buffer.append(hyperlink);
        buffer.append("]");
        return buffer.toString();
    }
}
